/** SCORM 1.2 error codes and their descriptions. */
export const SCORM_12_ERRORS: Record<number, string> = {
  0: 'No error',
  101: 'General Exception',
  201: 'Invalid argument error',
  202: 'Element cannot have children',
  203: 'Element not an array. Cannot have count.',
  301: 'Not initialized',
  401: 'Not implemented error',
  402: 'Invalid set value, element is a keyword',
  403: 'Element is read only',
  404: 'Element is write only',
  405: 'Incorrect Data Type',
};

/** SCORM 2004 (4th Edition) error codes and their descriptions. */
export const SCORM_2004_ERRORS: Record<number, string> = {
  0: 'No Error',
  101: 'General Exception',
  102: 'General Initialization Failure',
  103: 'Already Initialized',
  104: 'Content Instance Terminated',
  111: 'General Termination Failure',
  112: 'Termination Before Initialization',
  113: 'Termination After Termination',
  122: 'Retrieve Data Before Initialization',
  123: 'Retrieve Data After Termination',
  132: 'Store Data Before Initialization',
  133: 'Store Data After Termination',
  142: 'Commit Before Initialization',
  143: 'Commit After Termination',
  201: 'General Argument Error',
  301: 'General Get Failure',
  351: 'General Set Failure',
  391: 'General Commit Failure',
  401: 'Undefined Data Model Element',
  402: 'Unimplemented Data Model Element',
  403: 'Data Model Element Value Not Initialized',
  404: 'Data Model Element Is Read Only',
  405: 'Data Model Element Is Write Only',
  406: 'Data Model Element Type Mismatch',
  407: 'Data Model Element Value Out Of Range',
  408: 'Data Model Dependency Not Established',
};
